name: Build & Deploy

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Deploy on Caprover
        run: |
          tar -cvf deploy.tar --exclude=./deploy.tar .
          npx caprover deploy -t ./deploy.tar -h https://captain.yugi.techdotium.online/ -p ${{secrets.CAPROVER_PASSWORD}} -a todo
        env:
          CI: true
